name: Gitleaks Secret Scan

on:
  pull_request:
  merge_group:

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout gitleaks config
        uses: actions/checkout@v4
        with:
          repository: vpi-digital-products/.github
          path: .gitleaks-config
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_ORG_LICENSE_KEY }}
          GITLEAKS_CONFIG: .gitleaks-config/.gitleaks.toml
