name: Gitleaks Secret Scan

on:
  pull_request:
  merge_group:

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_ORG_LICENSE_KEY }}
          GITLEAKS_CONFIG: ${{ github.workspace }}/.gitleaks-config/.gitleaks.toml
